name: nsrpo
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  # Python version
  - python=3.11
  
  # Core ML libraries - CPU version
  - pytorch::pytorch>=2.0.0,<2.2.0
  - pytorch::cpuonly
  - transformers>=4.30.0,<4.40.0
  
  # Scientific computing
  - numpy>=1.21.0,<1.27.0
  - scipy>=1.9.0,<1.12.0
  - pandas>=1.5.0,<2.2.0
  - scikit-learn>=1.0.0,<1.4.0
  
  # Statistical analysis
  - statsmodels>=0.14.0,<0.15.0
  
  # Visualization
  - matplotlib>=3.7.0,<3.9.0
  - seaborn>=0.12.0,<0.14.0
  
  # Utilities
  - pyyaml>=6.0
  - tqdm>=4.65.0
  - tensorboard>=2.13.0,<2.16.0
  
  # Development tools
  - pytest>=7.0.0,<8.0.0
  - pytest-cov>=4.0.0,<5.0.0
  - black>=23.0.0,<24.0.0
  - isort>=5.12.0,<6.0.0
  - flake8>=6.0.0,<7.0.0
  
  # Jupyter (optional)
  - jupyter
  - ipykernel
  
  # Pip dependencies
  - pip
  - pip:
    # Additional pip-only packages
    - accelerate>=0.20.0,<0.30.0
    - json5>=0.9.0,<1.0.0